version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Setting up Maven configuration"
      - cp ./settings.xml /root/.m2/settings.xml
      - cp ./pmd/pmd-ruleset.xml /root/.m2/pmd-ruleset.xml

  pre_build:
    commands:
      - echo "Fetching fresh CodeArtifact token"
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
        --domain java-webapp-maven-repo \
        --domain-owner 761018849945 \
        --query authorizationToken \
        --output text)

  build:
    commands:
      - echo "Building the project"
      - mvn clean install -DskipTests
      - mv webapp/target/webapp.war webapp/target/login.war

artifacts:
  files:
    - '**/*'
