version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Setting up Maven configuration for PMD"
      - cp ./pmd/pmd-ruleset.xml /root/.m2/pmd-ruleset.xml

  pre_build:
    commands:
      - echo "Logging into CodeArtifact"
      - aws codeartifact login --tool maven \
          --domain java-webapp-maven-repo \
          --domain-owner 761018849945 \
          --repository maven-central-store
      - echo "CodeArtifact login complete"

  build:
    commands:
      - echo "Running PMD analysis"
      - mvn clean pmd:pmd

artifacts:
  files:
    - '**/*'
